config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'about', to: 'pages#about'
  resources :articles#, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  get 'signup', to: 'users#new'
  #post 'users', to: 'users#create'
  resources :users, except: [:new]
  get 'login',to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]

end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: { minimum: 6, maximum: 100}
    validates :description, presence: true, length: { minimum: 6, maximum: 1000}
    
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :required_user, except: [:index, :show]
    before_action :required_same_user, only: [:edit, :update, :destroy]
    def show
        #@article = Article.find(params[:id])
    end

    def index 
        @articles = Article.paginate(page: params[:page], per_page: 5)

    end

    def new
        @article = Article.new
    end

    def edit
        #@article = Article.find(params[:id])
    end

    def create
        @article = Article.new(article_params)#params.require(:article).permit(:title, :description ))
        @article.user = current_user         # for adding new artile after association, for error user must exit.
       if @article.save
            flash[:notice] = "The articles was succefully created"
            redirect_to @article  #after saving this will show the information you just created
       else
        render 'new'
       end
    end

    def update
        #@article = Article.find(params[:id])
        if @article.update(article_params)#params.require(:article).permit(:title, :description ))
            flash[:notice] = "The articles was succefully updated"
            redirect_to @article  #after saving this will show the information you just created
       else
        render 'edit'
        end 
    end
    def destroy 
        #@article = Article.find(params[:id])
        @article.destroy
        redirect_to articles_path
    end 

    private

    def set_article
        @article = Article.find(params[:id])
    end
    def article_params
        params.require(:article).permit(:title, :description,category_ids:[] )
    end
    def required_same_user
        if current_user != @article.user && !current_user.admin?
            flash[:alert] = "You can only edit or delete your own article"
            redirect_to @article
        end
    end
end

app/views/articles/_article.html.erb
<table>
    <thead>
        <tr>
            <th>Title </th>
            <th>Description </th>
            <th colspan = '3'>Actions </th>
        </tr>
    </thead>
    <tbody>
        <% @articles.each do |article|%></br>
            <tr>
                    <%if article.user%>
                        Article by <%=link_to article.user.username,user_path(article.user)%>
                    <%end%>
                    
                    <%if article.categories.any?%>
                        <%= render article.categories%> 
                    <%end%>
                
                <td><%=article.title%></td>
                <td><%= article.description%></td>

                
                
                <td><%= link_to 'view', article_path(article)%> </td>
                <% if logged_in? && (article.user == current_user ||current_user.admin?)%>
                    <td><%= link_to 'Edit', edit_article_path(article)%> </td>
                    <td>
                        <%= link_to 'Delete', article_path(article), method: :delete,
                        data: {confirm: "Are you sure?"} %>
                        
                     </td>
                <%end%>
            </tr>
        <%end%>
    
    </tbody>
</table>    

app/views/articles/_form.html.erb
<%= render 'shared/error',obj: @article%>

<%= form_with(model:  @article, local: true)  do |f| %>
    <p>
        <%= f.label :Title%></br>
        <%= f.text_field :title%>
    </p>

    <p>
        <%= f.label :description%></br>
        <%= f.text_area :description%>
    </p>

    <p>
        <%= f.label :category %></br>
        <%= f.collection_select(:category_ids, Category.all, :id, :name,
        {prompt: "Choose your categories(can be empty)"},{multiple: true,size:4}) %>

    </p>

    <p>
        <%= f.submit :Update%></br>
        
    </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= render 'form' %>
<%= link_to 'Cancel and return to article listing ', articles_path %>

app/views/articles/index.html.erb
</br>
<%= render 'pages/nav'%>
<%= render 'article'%>
<%= will_paginate @articles %>

app/views/articles/new.html.erb
<h1> Article</h1>

<%= render 'form'%>
<%= link_to 'Return to article listing ', articles_path %>

app/views/articles/show.html.erb
<h4>This is show page of Articles</h4>
<p> <strong>Title:</strong> <%= @article.title %> </p>
<p> <strong>Description:</strong> <%= @article.description %> </p>

<h3>By<%=@article.user.username%></h3></br>
<%= link_to  gravatar_for(@article.user),user_path(@article.user)%></br></br>
<%if @article.categories.any?%>
    <%= render @article.categories%> 
<%end%>
</br>
<%if logged_in? && (@article.user == current_user || current_user.admin?)%>
    <%= link_to 'Edit', edit_article_path(@article)%> |
    <%= link_to 'Delete', article_path(@article), method: :delete, data: {confirm: "Are you sure?"} %>
<%end%> |
<%= link_to 'Return to articles ', articles_path %>