config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'about', to: 'pages#about'
  resources :articles#, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  get 'signup', to: 'users#new'
  #post 'users', to: 'users#create'
  resources :users, except: [:new]
  get 'login',to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]

end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories
    has_many :articles, through: :article_categories
    validates :name, presence: true, length: {minimum: 3, maximum: 25}
    validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index, :show]
    def new
        @category = Category.new()
    end
    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Catergory was successfully created"
            redirect_to @category
        else
            render 'new'
        end
    end 

    def index
        @categories = Category.paginate(page: params[:page], per_page: 4)
    end 

    def show
        @category = Category.find(params[:id])
        @articles = @category.articles.paginate(page: params[:page], per_page: 3)
    end
    def edit 
        @category = Category.find(params[:id])
    end
    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:notice] = "Catergory was successfully updated"
            redirect_to @category
        else
            render 'edit'
        end
    end
    

    private
    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
      if  !(logged_in? && current_user.admin?)
        flash[:alert]= "only admin can performe this action"
        redirect_to categories_path
      end
    end
end

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category)%> 

app/views/categories/_form.html.erb
<%= render 'shared/error',obj: @category %>

<%= form_with(model:  @category, local: true)  do |f| %>
    <p>
        <%= f.label :name %></br>
        <%= f.text_field :name %>
    </p>
    <p>
        <%= f.submit :Create%></br>
    </p>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit category</h1>
<%= render 'form'%>

app/views/categories/index.html.erb
<h1>Categories</h1>

<table>
    <thead>
        <tr>
            <th>Name </th>
         </tr>
    </thead>
    <tbody>
        <% @categories.each do |category|%>
            <tr>    
                <td><%=link_to category.name, category_path(category)%></td>
                 <td> <%= pluralize(category.articles.count,"article")%> </td>
            </tr>
        <%end%>
    </tbody>
</table>    
<%= will_paginate @categories %>

app/views/categories/new.html.erb
<h1>Create new category</h1>
<%= render 'form'%>

app/views/categories/show.html.erb
<h1>category<%= @category.name%>'s Profile</h1>
                

<h3> Article</h3>

<%= render 'articles/article'%>
<%if logged_in? && current_user.admin?%>
    <%= link_to 'Edit category', edit_category_path(@category)%> 
<%end%>
<%= will_paginate @articles %>